server:
  port: 8080

spring:
  application:
    name: signal-buddy

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${DB_URL}
    #    # createDatabaseIfNotExist=true ??????? ?? ?? ??
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # ???? ??? ???? ???? ??? ?? ?? ???? ???.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # ???? ??? ?? ???? DB? ????? ??
    properties:
      hibernate:
        show_sql: true
#        format_sql: true # ??? ??

springdoc:
  swagger-ui:
    groups-order: DESC # ?? ??? ?????? ??
    tags-sorter: alpha # ??? ??? ??? ??
    operations-sorter: method # HTTP ???(GET, POST ?) ??? ??
    disable-swagger-default-url: true # ?? Swagger URL ????
    display-request-duration: true # ??? ?? ??? ??
    defaultModelsExpandDepth: 2 # ?? ??? ?? ?? ??
    defaultModelExpandDepth: 2 # ?? ??? ?? ?? ??
  api-docs:
    path: /api-docs # API ?? ?? ??
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true # JSON? ??? ??
#  paths-to-match:
#    - /api/v1/** # ?? ??? API? ??